// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
    public const string achievement_hands_on_2 = "CgkIp4-6pbEUEAIQDw"; // <GPGSID>
    public const string leaderboard_level = "CgkIp4-6pbEUEAIQAg"; // <GPGSID>
    public const string achievement_valley_depths = "CgkIp4-6pbEUEAIQBA"; // <GPGSID>
    public const string achievement_hands_on_1 = "CgkIp4-6pbEUEAIQDg"; // <GPGSID>
    public const string achievement_crate_collector_1 = "CgkIp4-6pbEUEAIQCw"; // <GPGSID>
    public const string achievement_sparkling_sweep_3 = "CgkIp4-6pbEUEAIQEw"; // <GPGSID>
    public const string achievement_crate_collector_3 = "CgkIp4-6pbEUEAIQDQ"; // <GPGSID>
    public const string achievement_sparkling_sweep_1 = "CgkIp4-6pbEUEAIQEQ"; // <GPGSID>
    public const string achievement_sparkling_sweep_2 = "CgkIp4-6pbEUEAIQEg"; // <GPGSID>
    public const string achievement_money_hoarder_3 = "CgkIp4-6pbEUEAIQCg"; // <GPGSID>
    public const string achievement_money_hoarder_2 = "CgkIp4-6pbEUEAIQCQ"; // <GPGSID>
    public const string achievement_money_hoarder_1 = "CgkIp4-6pbEUEAIQCA"; // <GPGSID>
    public const string achievement_crate_collector_2 = "CgkIp4-6pbEUEAIQDA"; // <GPGSID>
    public const string achievement_hands_on_3 = "CgkIp4-6pbEUEAIQEA"; // <GPGSID>
    public const string achievement_level_climber_2 = "CgkIp4-6pbEUEAIQBg"; // <GPGSID>
    public const string achievement_level_climber_3 = "CgkIp4-6pbEUEAIQBw"; // <GPGSID>
    public const string achievement_arctic_cold = "CgkIp4-6pbEUEAIQAw"; // <GPGSID>
    public const string achievement_level_climber_1 = "CgkIp4-6pbEUEAIQBQ"; // <GPGSID>

}

